### ISSUE TITLE
program stuck after ReadRegisters both exampal 2 as RX  and  9 as TX

### ISSUE THREAD

**Issue by borseyogesh1436** [LoRaTracker/SX126X#1]

**Comment by StuartsProjects** [comment]
The program sticking at that point suggests the SPI bus is not working or wired correctly, try the program '1_SX126XLT_LoRa_Register_Test' as a first test. 

Note that the particular Dorji SX1262 module you are using has a pin called SW that needs to be set high to power the RX\TX switch.  

I presume your using an atmega328AU, never heard of a atmega238AU.

**Comment by borseyogesh1436** [comment]
thanks for the prompt reply,
sorry for typing mistake, I am using atmega328AU.
I can implement your suggestions and get back to you.

when I am using another library it's working on both for  Lora RX and TX 
there is no need to set SW pin high and I just copy some function from your library regarding sleep and wakeup and i am getting 2.7mA in sleep mode and after wakeup it takes around 45.0mA 

https://youtu.be/2bqAG-Vlkeo

**Comment by borseyogesh1436** [comment]
as you `suggested,`
I test '1_SX126XLT_LoRa_Register_Test' 
 its detecting Lora module in both stats of SW pin as high and not connected.

`12:01:40 Dec 28 2019
V1.0

1_SX126XLT_LoRa_Register_Test Starting
Device found
Frequency at reset 915000000
Reg    0  1  2  3  4  5  6  7  8  9  A  B  C  D  E  F
0x680  04 C0 00 40 00 00 00 00 00 00 00 00 00 00 00 00 
0x690  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
0x6A0  00 02 41 55 00 14 7B 08 20 0A 20 07 00 00 00 00 
0x6B0  00 00 00 00 04 00 14 20 21 00 C6 0F 1D 0F 10 21 
0x6C0  97 23 52 25 56 53 65 64 00 00 00 00 00 00 00 00 
0x6D0  00 0C 03 00 00 00 00 00 00 00 00 00 00 00 00 00 
0x6E0  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
0x6F0  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
0x700  00 00 0C 57 02 04 00 00 00 00 00 00 00 00 00 00 
0x710  00 00 00 00 00 00 00 00 00 7F 28 00 00 FF 00 01 
0x720  37 2A 53 00 80 00 40 00 00 0A 0A 00 00 00 00 00 
0x730  24 00 21 28 B0 30 0D 1A 09 70 00 08 58 0B 19 0A 
0x740  14 24 6A 96 00 18 00 00 00 00 00 00 00 00 00 00 
0x750  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
0x760  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
0x770  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
0x780  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
0x790  00 00 00 00 00 00 00 28 4C 09 37 00 00 00 00 00 
0x7A0  0E 03 00 3C 00 05 01 56 00 00 00 00 00 00 00 00 
0x7B0  02 03 02 03 05 08 06 04 02 FE FC FD 03 0B 13 0A 
0x7C0  00 3C 06 19 2A 07 61 09 02 04 21 28 02 00 00 00 
0x7D0  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
0x7E0  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
0x7F0  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
0x800  00 00 00 00 01 07 20 1E 00 10 19 04 0F FF 0F FF 
0x810  10 00 10 00 10 00 10 00 00 00 00 00 00 00 00 00 
0x820  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
0x830  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
0x840  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
0x850  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
0x860  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
0x870  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
0x880  03 00 00 5F 10 08 00 00 08 05 00 39 30 00 00 0C 
0x890  00 00 00 00 00 0F 0A 07 10 00 26 01 01 53 06 07 
0x8A0  10 00 AA 20 5A 04 F0 00 56 56 54 43 94 20 40 00 
0x8B0  00 83 11 00 01 04 0A 4C 14 0A 2F 01 6B FF FF 00 
0x8C0  00 A0 20 00 00 00 AC 00 1C 00 00 AB 05 30 00 00 
0x8D0  0C 14 14 40 06 00 00 10 C8 00 00 00 00 00 31 39 
0x8E0  90 39 0C 04 40 20 1C 18 03 00 05 04 03 02 01 01 
0x8F0  00 00 00 00 30 00 00 00 00 00 00 00 00 00 00 00 
0x900  30 00 00 00 00 00 00 00 00 00 00 00 24 04 47 04 
0x910  14 12 12 04 00 03 0A 00 15 35 09 00 02 1F 5F 08 
0x920  01 04 05 00 00 00 00 00 00 00 00 00 00 00 00 00 
Changed Frequency 434400000`

and I test '9_SX126XLT_LoRa_TX_and_Sleep' in both state of SW pin as high and not connected.
having same problem as before

` 12:20:30 Dec 28 2019

V1.0

9_SX126XLT_LoRa_Simple_TX_and_Sleep Starting
begin()
SX126XClass constructor instantiated successfully
NSS 0
NRESET 0
RFBUSY 0
DIO1 0
DIO2 0
DIO3 0
Pin_Init()
resetDevice()
checkDevice()
readRegister()
readRegisters()
checkBusy()
ReadRegisters
88E`
