### ISSUE TITLE
Frequency error reading

### ISSUE THREAD

**Issue by jgromes** [LoRaTracker/SX126X#2]
Hi, I noticed your library implements frequency error reading:

https://github.com/LoRaTracker/SX126X/blob/4a2e79bbbd50dec9ed1456d23a544bddb49fa791/src/SX126XLT.cpp#L2298-L2318

Where did you find information on how to implement it? There's nothing in the datasheet, I also asked on Semtech developer forums and a representative claimed frequency error was not implemented in SX126x.

**Comment by StuartsProjects** [comment]
The calculation came from the SX128X datasheet that predates the SX126X device. Semtech published code for how to calculate the frequency error for the SX128X, so with the SX126X being almost identical in command structure its seemed reasonable that the calculation of frequency error would be the same. The presence of the frequency error registers is clearly evident in Semtechs published code for the SX126X. 

Have you tried the code  ? 

Easy to check with these TCXO modules being so stable, run up a TX and RX pair, check the frequency error and then change the frequency of the TX to see if that change is reflected in the new error. 

The SX126X library here has been subsumed into a combined SX126X, SX127X, SX128X library here;

[](https://github.com/LoRaTracker/SX12XX-LoRa)

**Comment by jgromes** [comment]
Wow, Semtech really needs to fix the docs for SX126x, in a major way.

I haven't tried it yet, I'm asking mainly because they claimed that frequency error measurement was not implemented in SX126x: https://lora-developers.semtech.com/knowledge-base/forum/viewthread/96/

Thanks!

**Comment by StuartsProjects** [comment]
Can you send me an email direct, you should be able to do so from the blog on the loratracker website.
